// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap/ytest"
	"github.com/qiniu/x/test"
)

const _ = true

type simple struct {
	ytest.Case
	*App
}
type App struct {
	ytest.App
}

func (this *App) Main() {
	_xgo_obj0 := &simple{App: this}
	ytest.XGot_App_Main(this, _xgo_obj0)
}
//line ytest/demo/match/simple/simple_yapt.gox:1
func (this *simple) Main() {
//line ytest/demo/match/simple/simple_yapt.gox:1:1
	id := test.XGox_Var_Cast__0[int]()
//line ytest/demo/match/simple/simple_yapt.gox:2:1
	test.XGot_Case_MatchAny(this, id, 1+2)
//line ytest/demo/match/simple/simple_yapt.gox:3:1
	test.XGot_Case_MatchAny(this, id, 3)
//line ytest/demo/match/simple/simple_yapt.gox:4:1
	fmt.Println(id)
//line ytest/demo/match/simple/simple_yapt.gox:6:1
	test.XGot_Case_MatchAny(this, id, 5)
}
func main() {
	new(App).Main()
}
