// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type blog struct {
	yap.App
}
//line demo/classfile_nestetemplate/blog_yap.gox:1
func (this *blog) MainEntry() {
//line demo/classfile_nestetemplate/blog_yap.gox:1:1
	this.Get("/", func(ctx *yap.Context) {
//line demo/classfile_nestetemplate/blog_yap.gox:2:1
		ctx.Html__1(`<html><body>Hello, <a href="/p/123">YAP</a>!</body></html>`)
	})
//line demo/classfile_nestetemplate/blog_yap.gox:4:1
	this.Get("/p/:id", func(ctx *yap.Context) {
//line demo/classfile_nestetemplate/blog_yap.gox:5:1
		ctx.Yap__1("blog", map[string]string{"Id": ctx.Param("id")})
	})
//line demo/classfile_nestetemplate/blog_yap.gox:10:1
	this.Run(":8888")
}
func (this *blog) Main() {
	yap.Gopt_App_Main(this)
}
func main() {
	new(blog).Main()
}
