// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap/ytest"
	"github.com/goplus/yap/ytest/auth/bearer"
	"github.com/qiniu/x/stringutil"
	"github.com/qiniu/x/test"
	"testing"
)

type case_example struct {
	ytest.CaseApp
}
//line ytest/demo/_example/example_ytest.gox:3
func (this *case_example) Main() {
//line ytest/demo/_example/example_ytest.gox:3:1
	this.Host__0("https://example.com", "http://localhost:8080")
//line ytest/demo/_example/example_ytest.gox:4:1
	testauth := bearer.New("...")
//line ytest/demo/_example/example_ytest.gox:6:1
	this.DefaultHeader.Set("User-Agent", "yaptest/0.7")
//line ytest/demo/_example/example_ytest.gox:8:1
	this.Run("urlWithVar", func() {
//line ytest/demo/_example/example_ytest.gox:9:1
		id := "123"
//line ytest/demo/_example/example_ytest.gox:10:1
		this.Get(stringutil.Concat("https://example.com/p/", id))
//line ytest/demo/_example/example_ytest.gox:11:1
		this.Send()
//line ytest/demo/_example/example_ytest.gox:12:1
		fmt.Println("code:", this.Resp().Code())
//line ytest/demo/_example/example_ytest.gox:13:1
		fmt.Println("body:", this.Resp().Body())
	})
//line ytest/demo/_example/example_ytest.gox:16:1
	this.Run("matchWithVar", func() {
//line ytest/demo/_example/example_ytest.gox:17:1
		code := test.XGox_Var_Cast__0[int]()
//line ytest/demo/_example/example_ytest.gox:18:1
		id := "123"
//line ytest/demo/_example/example_ytest.gox:19:1
		this.Get(stringutil.Concat("https://example.com/p/", id))
//line ytest/demo/_example/example_ytest.gox:20:1
		this.RetWith(code)
//line ytest/demo/_example/example_ytest.gox:21:1
		fmt.Println("code:", code)
//line ytest/demo/_example/example_ytest.gox:22:1
		test.XGot_Case_MatchAny(this, code, 200)
	})
//line ytest/demo/_example/example_ytest.gox:25:1
	this.Run("postWithAuth", func() {
//line ytest/demo/_example/example_ytest.gox:26:1
		id := "123"
//line ytest/demo/_example/example_ytest.gox:27:1
		title := "title"
//line ytest/demo/_example/example_ytest.gox:28:1
		author := "author"
//line ytest/demo/_example/example_ytest.gox:29:1
		this.Post(stringutil.Concat("https://example.com/p/", id))
//line ytest/demo/_example/example_ytest.gox:30:1
		this.Auth(testauth)
//line ytest/demo/_example/example_ytest.gox:31:1
		this.Json(map[string]string{"title": title, "author": author})
//line ytest/demo/_example/example_ytest.gox:35:1
		this.RetWith(200)
//line ytest/demo/_example/example_ytest.gox:36:1
		fmt.Println("body:", this.Resp().Body())
	})
//line ytest/demo/_example/example_ytest.gox:39:1
	this.Run("matchJsonObject", func() {
//line ytest/demo/_example/example_ytest.gox:40:1
		title := test.XGox_Var_Cast__0[string]()
//line ytest/demo/_example/example_ytest.gox:41:1
		author := test.XGox_Var_Cast__0[string]()
//line ytest/demo/_example/example_ytest.gox:42:1
		id := "123"
//line ytest/demo/_example/example_ytest.gox:43:1
		this.Get(stringutil.Concat("https://example.com/p/", id))
//line ytest/demo/_example/example_ytest.gox:44:1
		this.RetWith(200)
//line ytest/demo/_example/example_ytest.gox:45:1
		this.Json(map[string]*test.Var__0[string]{"title": title, "author": author})
//line ytest/demo/_example/example_ytest.gox:49:1
		fmt.Println("title:", title)
//line ytest/demo/_example/example_ytest.gox:50:1
		fmt.Println("author:", author)
	})
}
func Test_example(t *testing.T) {
	ytest.XGot_CaseApp_TestMain(new(case_example), t)
}
