// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap"
	"github.com/qiniu/x/test"
	"github.com/goplus/yap/ytest"
	"github.com/qiniu/x/stringutil"
)

const _ = true

type get_p_id struct {
	yap.Handler
	*AppV2
}
type hello struct {
	ytest.Case
	*App
}
type AppV2 struct {
	yap.AppV2
}
//line ytest/demo/match/diveinto/get_p_#id.yap:1
func (this *get_p_id) Main(_gop_arg0 *yap.Context) {
	this.Handler.Main(_gop_arg0)
//line ytest/demo/match/diveinto/get_p_#id.yap:1:1
	this.Json__1(map[string]string{"id": this.Gop_Env("id")})
}
func (this *get_p_id) Classfname() string {
	return "get_p_#id"
}
func (this *get_p_id) Classclone() yap.HandlerProto {
	_gop_ret := *this
	return &_gop_ret
}

type App struct {
	ytest.App
}
//line ytest/demo/match/diveinto/hello_yapt.gox:1
func (this *hello) Main() {
//line ytest/demo/match/diveinto/hello_yapt.gox:1:1
	this.Mock("foo.com", new(AppV2))
//line ytest/demo/match/diveinto/hello_yapt.gox:3:1
	id := "123"
//line ytest/demo/match/diveinto/hello_yapt.gox:4:1
	this.Get(stringutil.Concat("http://foo.com/p/", id))
//line ytest/demo/match/diveinto/hello_yapt.gox:6:1
	this.Send()
//line ytest/demo/match/diveinto/hello_yapt.gox:7:1
	test.Gopt_Case_MatchTBase(this, 200, this.Resp().Code())
//line ytest/demo/match/diveinto/hello_yapt.gox:8:1
	test.Gopt_Case_MatchTBase(this, "application/json", this.Resp().Header().Get("Content-Type"))
//line ytest/demo/match/diveinto/hello_yapt.gox:9:1
	test.Gopt_Case_MatchAny(this, map[string]string{"id": id}, this.Resp().Body())
//line ytest/demo/match/diveinto/hello_yapt.gox:13:1
	fmt.Println("OK")
}
func (this *AppV2) Main() {
	yap.Gopt_AppV2_Main(this, new(get_p_id))
}
func (this *App) Main() {
	ytest.Gopt_App_Main(this, new(hello))
}
func main() {
	new(App).Main()
}
