// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"fmt"

	"github.com/goplus/yap"
	"github.com/goplus/yap/ytest"
	"github.com/qiniu/x/stringutil"
	"github.com/qiniu/x/test"
)

const _ = true

type get_p_id struct {
	yap.Handler
	*AppV2
}
type hello struct {
	ytest.Case
	*App
}
type AppV2 struct {
	yap.AppV2
}

func (this *AppV2) Main() {
	_xgo_obj0 := &get_p_id{AppV2: this}
	yap.XGot_AppV2_Main(this, _xgo_obj0)
}

//line ytest/demo/match/diveinto/get_p_#id.yap:1
func (this *get_p_id) Main(_xgo_arg0 *yap.Context) {
	this.Handler.Main(_xgo_arg0)
//line ytest/demo/match/diveinto/get_p_#id.yap:1:1
	this.Json__1(map[string]string{"id": this.XGo_Env("id")})
}
func (this *get_p_id) Classfname() string {
	return "get_p_#id"
}
func (this *get_p_id) Classclone() yap.HandlerProto {
	_xgo_ret := *this
	return &_xgo_ret
}

type App struct {
	ytest.App
}

func (this *App) Main() {
	_xgo_obj0 := &hello{App: this}
	ytest.XGot_App_Main(this, _xgo_obj0)
}

//line ytest/demo/match/diveinto/hello_yapt.gox:1
func (this *hello) Main() {
//line ytest/demo/match/diveinto/hello_yapt.gox:1:1
	this.Mock("foo.com", new(AppV2))
//line ytest/demo/match/diveinto/hello_yapt.gox:3:1
	id := "123"
//line ytest/demo/match/diveinto/hello_yapt.gox:4:1
	this.Get(stringutil.Concat("http://foo.com/p/", id))
//line ytest/demo/match/diveinto/hello_yapt.gox:6:1
	this.Send()
//line ytest/demo/match/diveinto/hello_yapt.gox:7:1
	test.XGot_Case_MatchTBase(this, 200, this.Resp().Code())
//line ytest/demo/match/diveinto/hello_yapt.gox:8:1
	test.XGot_Case_MatchTBase(this, "application/json", this.Resp().Header().Get("Content-Type"))
//line ytest/demo/match/diveinto/hello_yapt.gox:9:1
	test.XGot_Case_MatchAny(this, map[string]string{"id": id}, this.Resp().Body())
//line ytest/demo/match/diveinto/hello_yapt.gox:13:1
	fmt.Println("OK")
}
func main() {
	new(App).Main()
}
