// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap"
	"github.com/goplus/yap/ytest"
	"github.com/qiniu/x/stringutil"
)

const _ = true

type get_p_id struct {
	yap.Handler
	*AppV2
}
type hello struct {
	ytest.Case
	*App
}
type AppV2 struct {
	yap.AppV2
}
//line ytest/demo/match/hello/get_p_#id.yap:1
func (this *get_p_id) Main(_gop_arg0 *yap.Context) {
	this.Handler.Main(_gop_arg0)
//line ytest/demo/match/hello/get_p_#id.yap:1:1
	this.Json__1(map[string]string{"id": this.Gop_Env("id")})
}
func (this *get_p_id) Classfname() string {
	return "get_p_#id"
}

type App struct {
	ytest.App
}
//line ytest/demo/match/hello/hello_yapt.gox:1
func (this *hello) Main() {
//line ytest/demo/match/hello/hello_yapt.gox:1:1
	this.Mock("foo.com", new(AppV2))
//line ytest/demo/match/hello/hello_yapt.gox:3:1
	id := "123"
//line ytest/demo/match/hello/hello_yapt.gox:4:1
	this.Get(stringutil.Concat("http://foo.com/p/", id))
//line ytest/demo/match/hello/hello_yapt.gox:5:1
	this.RetWith(200)
//line ytest/demo/match/hello/hello_yapt.gox:6:1
	this.Json(map[string]string{"id": id})
//line ytest/demo/match/hello/hello_yapt.gox:9:1
	fmt.Println("OK")
}
func (this *hello) Classfname() string {
	return "hello"
}
func (this *AppV2) Main() {
	yap.Gopt_AppV2_Main(this, new(get_p_id))
}
func (this *App) Main() {
	ytest.Gopt_App_Main(this, new(hello))
}
func main() {
}
