// Code generated by gop (Go+); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type get_p_id struct {
	yap.Handler
	*AppV2
}
type AppV2 struct {
	yap.AppV2
}
//line ytest/demo/jwtdemo/get_p_#id.yap:1
func (this *get_p_id) Main(_gop_arg0 *yap.Context) {
	this.Handler.Main(_gop_arg0)
//line ytest/demo/jwtdemo/get_p_#id.yap:1:1
	this.Json__1(map[string]string{"id": this.Gop_Env("id")})
}
func (this *get_p_id) Classfname() string {
	return "get_p_#id"
}
func (this *AppV2) Main() {
	yap.Gopt_AppV2_Main(this, new(get_p_id))
}
func main() {
	new(AppV2).Main()
}
