// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/goplus/yap"

const _ = true

type get_p_id struct {
	yap.Handler
	*AppV2
}
type AppV2 struct {
	yap.AppV2
}

func (this *AppV2) Main() {
	_xgo_obj0 := &get_p_id{AppV2: this}
	yap.XGot_AppV2_Main(this, _xgo_obj0)
}
//line ytest/demo/jwtdemo/get_p_#id.yap:1
func (this *get_p_id) Main(_xgo_arg0 *yap.Context) {
	this.Handler.Main(_xgo_arg0)
//line ytest/demo/jwtdemo/get_p_#id.yap:1:1
	this.Json__1(map[string]string{"id": this.XGo_Env("id")})
}
func (this *get_p_id) Classfname() string {
	return "get_p_#id"
}
func (this *get_p_id) Classclone() yap.HandlerProto {
	_xgo_ret := *this
	return &_xgo_ret
}
func main() {
	new(AppV2).Main()
}
