// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"github.com/goplus/yap"
	"github.com/qiniu/x/http/fs"
)

const _ = true

type AppV2 struct {
	yap.AppV2
}
//line demo/classfile2_statichttp/main.yap:3
func (this *AppV2) MainEntry() {
//line demo/classfile2_statichttp/main.yap:3:1
	this.Static__2("/", fs.Http("https://goplus.org"), false)
//line demo/classfile2_statichttp/main.yap:4:1
	this.Run(":8080")
}
func main() {
	yap.Gopt_AppV2_Main(new(AppV2))
}
