// Code generated by xgo (XGo); DO NOT EDIT.

package main

import (
	"github.com/goplus/yap"
	"github.com/qiniu/x/http/fs"
)

const _ = true

type AppV2 struct {
	yap.AppV2
}
//line demo/classfile2_statichttp/main.yap:3
func (this *AppV2) MainEntry() {
//line demo/classfile2_statichttp/main.yap:3:1
	this.Static__2("/", fs.Http("https://xgo.dev"), false)
//line demo/classfile2_statichttp/main.yap:4:1
	this.Run(":8080")
}
func (this *AppV2) Main() {
	yap.XGot_AppV2_Main(this)
}
func main() {
	new(AppV2).Main()
}
