// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"github.com/goplus/yap/test"
	"github.com/goplus/yap/ydb"
	_ "github.com/goplus/yap/ydb/mysql"
	_ "github.com/goplus/yap/ydb/sqlite3"
	"math/rand"
	"strconv"
	"time"
)

const _ = true

type ArticleEntry struct {
	Id     string `CHAR(32) UNIQUE`
	Author string `CHAR(24) INDEX`
	Title  string
	Ctime  time.Time `DATETIME INDEX`
}
type Article struct {
	ArticleEntry
	Body []byte `LONGBLOB`
}
type Tag struct {
	Name string `CHAR(24) UNIQUE(doc)`
	Doc  string `CHAR(32)`
}
type User struct {
	Id       string `id CHAR(32) UNIQUE`
	Spwd     string
	Salt     string
	Nickname string
	Email    string    `CHAR(64) INDEX`
	Tel      string    `CHAR(16) INDEX`
	Born     time.Time `INDEX`
	Ctime    time.Time `DATETIME(6) INDEX`
}
type article struct {
	ydb.Sql
}
type user struct {
	ydb.Sql
}

func main() {
//line ydb/demo/foo/user_ydb.gox:23:1
	ydb.Gopt_AppGen_Main(new(ydb.AppGen), new(article), new(user))
}
//line ydb/demo/foo/article_ydb.gox:20
func (this *article) Main() {
//line ydb/demo/foo/article_ydb.gox:20:1
	this.Engine__0("mysql")
//line ydb/demo/foo/article_ydb.gox:22:1
	ydb.Gopt_Sql_Gopx_Table[Article](this, "v0.1.0")
//line ydb/demo/foo/article_ydb.gox:23:1
	this.From("oldart v0.9.1", func() {
	})
//line ydb/demo/foo/article_ydb.gox:28:1
	ydb.Gopt_Sql_Gopx_Table[Tag](this, "v0.1.0")
//line ydb/demo/foo/article_ydb.gox:30:1
	this.Class("Articles", func() {
//line ydb/demo/foo/article_ydb.gox:31:1
		this.Use("article")
//line ydb/demo/foo/article_ydb.gox:33:1
		add := this.Api("add", func(doc *Article) error {
//line ydb/demo/foo/article_ydb.gox:34:1
			this.Insert__1(doc)
//line ydb/demo/foo/article_ydb.gox:35:1
			return nil
		})
//line ydb/demo/foo/article_ydb.gox:38:1
		doc1 := &Article{}
//line ydb/demo/foo/article_ydb.gox:39:1
		doc1.Id, doc1.Author, doc1.Title = "123", "abc", "title1"
//line ydb/demo/foo/article_ydb.gox:40:1
		add(doc1)
//line ydb/demo/foo/article_ydb.gox:41:1
		this.Ret__0(nil)
//line ydb/demo/foo/article_ydb.gox:43:1
		add(doc1)
//line ydb/demo/foo/article_ydb.gox:44:1
		this.Ret__1(ydb.ErrDuplicated)
//line ydb/demo/foo/article_ydb.gox:46:1
		doc2 := &Article{}
//line ydb/demo/foo/article_ydb.gox:47:1
		doc2.Id, doc2.Author, doc2.Title = "124", "efg", "title2"
//line ydb/demo/foo/article_ydb.gox:48:1
		add(doc2)
//line ydb/demo/foo/article_ydb.gox:49:1
		this.Ret__0(nil)
//line ydb/demo/foo/article_ydb.gox:51:1
		doc3 := &Article{}
//line ydb/demo/foo/article_ydb.gox:52:1
		doc3.Id, doc3.Author, doc3.Title = "125", "efg", "title3"
//line ydb/demo/foo/article_ydb.gox:53:1
		add(doc3)
//line ydb/demo/foo/article_ydb.gox:54:1
		this.Ret__0(nil)
//line ydb/demo/foo/article_ydb.gox:56:1
		doc4 := &Article{}
//line ydb/demo/foo/article_ydb.gox:57:1
		doc4.Id, doc4.Author, doc4.Title = "225", "abc", "title4"
//line ydb/demo/foo/article_ydb.gox:58:1
		add(doc4)
//line ydb/demo/foo/article_ydb.gox:59:1
		this.Ret__0(nil)
//line ydb/demo/foo/article_ydb.gox:61:1
		doc5 := &Article{}
//line ydb/demo/foo/article_ydb.gox:62:1
		doc5.Id, doc5.Author, doc5.Title = "555", "abc", "title5"
//line ydb/demo/foo/article_ydb.gox:63:1
		add(doc5)
//line ydb/demo/foo/article_ydb.gox:64:1
		this.Ret__0(nil)
//line ydb/demo/foo/article_ydb.gox:66:1
		get := this.Api("get", func(docId string) (doc Article, err error) {
//line ydb/demo/foo/article_ydb.gox:67:1
			this.Query__1("id=?", docId)
//line ydb/demo/foo/article_ydb.gox:68:1
			this.Ret__1(&doc)
//line ydb/demo/foo/article_ydb.gox:69:1
			return
		})
//line ydb/demo/foo/article_ydb.gox:72:1
		get(doc1.Id)
//line ydb/demo/foo/article_ydb.gox:73:1
		this.Ret__1(doc1, nil)
//line ydb/demo/foo/article_ydb.gox:75:1
		get(doc2.Id)
//line ydb/demo/foo/article_ydb.gox:76:1
		this.Ret__1(doc2, nil)
//line ydb/demo/foo/article_ydb.gox:78:1
		get("unknown")
//line ydb/demo/foo/article_ydb.gox:79:1
		test.Gopt_Case_Match__4(this, this.Out(1), ydb.ErrNoRows)
//line ydb/demo/foo/article_ydb.gox:81:1
		setTags := this.Api("setTags", func(docId string, tags ...string) error {
//line ydb/demo/foo/article_ydb.gox:82:1
			var oldtags []string
//line ydb/demo/foo/article_ydb.gox:83:1
			this.Query__1("tag.doc=?", docId)
//line ydb/demo/foo/article_ydb.gox:84:1
			this.Ret__1("tag.name", &oldtags)
//line ydb/demo/foo/article_ydb.gox:86:1
			tagsAdd, tagsDel := Diff(tags, oldtags)
//line ydb/demo/foo/article_ydb.gox:87:1
			this.Delete__1("tag.name=?", tagsDel)
//line ydb/demo/foo/article_ydb.gox:88:1
			this.Insert__1("doc", docId, "tag.name", tagsAdd)
//line ydb/demo/foo/article_ydb.gox:89:1
			return nil
		})
//line ydb/demo/foo/article_ydb.gox:92:1
		tags := this.Api("tags", func(docId string) (tags []string, err error) {
//line ydb/demo/foo/article_ydb.gox:93:1
			this.Query__1("tag.doc=?", docId)
//line ydb/demo/foo/article_ydb.gox:94:1
			this.Ret__1("tag.name", &tags)
//line ydb/demo/foo/article_ydb.gox:95:1
			return
		})
//line ydb/demo/foo/article_ydb.gox:97:1
		_ = tags
//line ydb/demo/foo/article_ydb.gox:99:1
		setTags(doc1.Id, "tag1", "tag2")
//line ydb/demo/foo/article_ydb.gox:100:1
		this.Ret__0(nil)
//line ydb/demo/foo/article_ydb.gox:105:1
		listByTag := this.Api("listByTag", func(tag string) (result []ArticleEntry) {
//line ydb/demo/foo/article_ydb.gox:106:1
			var ids []string
//line ydb/demo/foo/article_ydb.gox:107:1
			this.Query__1("tag.name=?", tag)
//line ydb/demo/foo/article_ydb.gox:108:1
			this.Ret__1("tag.doc", &ids)
//line ydb/demo/foo/article_ydb.gox:110:1
			this.Query__1("id=?", ids)
//line ydb/demo/foo/article_ydb.gox:111:1
			this.Ret__1(&result)
//line ydb/demo/foo/article_ydb.gox:112:1
			return
		})
//line ydb/demo/foo/article_ydb.gox:114:1
		_ = listByTag
//line ydb/demo/foo/article_ydb.gox:116:1
		listByAuthor := this.Api("listByAuthor", func(author string) (result []ArticleEntry) {
//line ydb/demo/foo/article_ydb.gox:117:1
			this.Query__1("author=?", author)
//line ydb/demo/foo/article_ydb.gox:118:1
			this.Ret__1(&result)
//line ydb/demo/foo/article_ydb.gox:119:1
			return
		})
//line ydb/demo/foo/article_ydb.gox:121:1
		_ = listByAuthor
	})
}

var ErrNoEmailAndTel = errors.New("no email and telephone")
var rnd = rand.New(rand.NewSource(time.Now().UnixMicro()))
//line ydb/demo/foo/foo.gop:19:1
func Rand() string {
//line ydb/demo/foo/foo.gop:20:1
	return strconv.FormatInt(rnd.Int63(), 36)
}
//line ydb/demo/foo/foo.gop:23:1
func Hs256(pwd string, salt string) string {
//line ydb/demo/foo/foo.gop:24:1
	b := hmac.New(sha256.New, []byte(salt)).Sum([]byte(pwd))
//line ydb/demo/foo/foo.gop:25:1
	return base64.RawURLEncoding.EncodeToString(b)
}
//line ydb/demo/foo/foo.gop:28:1
func Diff(new []string, old []string) (add []string, del []string) {
//line ydb/demo/foo/foo.gop:29:1
	return
}
//line ydb/demo/foo/user_ydb.gox:19
func (this *user) Main() {
//line ydb/demo/foo/user_ydb.gox:19:1
	this.Engine__0("sqlite3")
//line ydb/demo/foo/user_ydb.gox:21:1
	ydb.Gopt_Sql_Gopx_Table[User](this, "user v0.1.0")
//line ydb/demo/foo/user_ydb.gox:23:1
	this.Class("Users", func() {
//line ydb/demo/foo/user_ydb.gox:24:1
		this.Use("user")
//line ydb/demo/foo/user_ydb.gox:26:1
		register := this.Api("register", func(id string, pwd string, nickname string, email string, tel string, ctime time.Time) error {
//line ydb/demo/foo/user_ydb.gox:27:1
			if email == "" && tel == "" {
//line ydb/demo/foo/user_ydb.gox:28:1
				return ErrNoEmailAndTel
			}
//line ydb/demo/foo/user_ydb.gox:30:1
			this.Limit__2(3, "email=?", email)
//line ydb/demo/foo/user_ydb.gox:31:1
			this.Limit__2(3, "tel=?", tel)
//line ydb/demo/foo/user_ydb.gox:33:1
			salt := Rand()
//line ydb/demo/foo/user_ydb.gox:34:1
			spwd := Hs256(pwd, salt)
//line ydb/demo/foo/user_ydb.gox:35:1
			this.Insert__1(&User{Id: id, Spwd: spwd, Salt: salt, Nickname: nickname, Email: email, Tel: tel, Ctime: ctime})
//line ydb/demo/foo/user_ydb.gox:36:1
			return nil
		})
//line ydb/demo/foo/user_ydb.gox:38:1
		register("user", "pwd", "nickname", "", "", time.Now())
//line ydb/demo/foo/user_ydb.gox:39:1
		this.Ret__1(ErrNoEmailAndTel)
//line ydb/demo/foo/user_ydb.gox:40:1
		register("user", "pwd", "nickname", "user@foo.com", "", time.Now())
//line ydb/demo/foo/user_ydb.gox:41:1
		this.Ret__0(nil)
//line ydb/demo/foo/user_ydb.gox:42:1
		register("user", "pwd", "nickname", "user@foo.com", "13500000000", time.Now())
//line ydb/demo/foo/user_ydb.gox:43:1
		this.Ret__1(ydb.ErrDuplicated)
//line ydb/demo/foo/user_ydb.gox:45:1
		login := this.Api("login", func(id string, pwd string) bool {
//line ydb/demo/foo/user_ydb.gox:46:1
			var spwd, salt string
//line ydb/demo/foo/user_ydb.gox:47:1
			this.Query__1("id=?", id)
//line ydb/demo/foo/user_ydb.gox:48:1
			this.Ret__1("salt", &salt, "spwd", &spwd)
//line ydb/demo/foo/user_ydb.gox:49:1
			return Hs256(pwd, salt) == spwd
		})
//line ydb/demo/foo/user_ydb.gox:51:1
		login("", "")
//line ydb/demo/foo/user_ydb.gox:52:1
		this.Ret__1(false)
//line ydb/demo/foo/user_ydb.gox:53:1
		login("user", "pwd")
//line ydb/demo/foo/user_ydb.gox:54:1
		this.Ret__1(true)
	})
}
