// Code generated by gop (Go+); DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goplus/yap/test"
	"github.com/goplus/yap/ytest"
	"github.com/qiniu/x/stringutil"
)

const _ = true

type wechat struct {
	ytest.Case
	*App
}
type App struct {
	ytest.App
}
//line cmd/wechat/wechat_yapt.gox:1
func (this *wechat) Main() {
//line cmd/wechat/wechat_yapt.gox:1:1
	this.Host__1("https://api.weixin.qq.com")
//line cmd/wechat/wechat_yapt.gox:3:1
	errcode := test.Gopx_Var_Cast__0[int]()
//line cmd/wechat/wechat_yapt.gox:4:1
	errmsg := test.Gopx_Var_Cast__0[string]()
//line cmd/wechat/wechat_yapt.gox:5:1
	token := test.Gopx_Var_Cast__0[string]()
//line cmd/wechat/wechat_yapt.gox:6:1
	expires := test.Gopx_Var_Cast__0[float64]()
//line cmd/wechat/wechat_yapt.gox:8:1
	this.Get(stringutil.Concat("/cgi-bin/token?grant_type=client_credential&appid=", this.Gop_Env("WECHAT_AK"), "&secret=", this.Gop_Env("WECHAT_SK")))
//line cmd/wechat/wechat_yapt.gox:9:1
	this.RetWith(200)
//line cmd/wechat/wechat_yapt.gox:10:1
	this.Json(map[string]interface{}{"errcode": errcode, "errmsg": errmsg, "access_token": token, "expires_in": expires})
//line cmd/wechat/wechat_yapt.gox:16:1
	if errcode.Ok() {
//line cmd/wechat/wechat_yapt.gox:17:1
		fmt.Println(errmsg)
	} else {
//line cmd/wechat/wechat_yapt.gox:19:1
		fmt.Println(token, expires)
	}
}
func (this *App) Main() {
	ytest.Gopt_App_Main(this, new(wechat))
}
func main() {
	new(App).Main()
}
