// Code generated by xgo (XGo); DO NOT EDIT.

package main

import "github.com/goplus/yap/ytest"

const _ = true

type wechat struct {
	ytest.Case
	*App
}
type App struct {
	ytest.App
}

func (this *App) Main() {
	_xgo_obj0 := &wechat{App: this}
	ytest.XGot_App_Main(this, _xgo_obj0)
}
func (this *wechat) Main() {
}
func main() {
	new(App).Main()
}
